### ISSUE TITLE
Support for existing files (and directories)

### ISSUE THREAD

**Issue by matt-matt1** [madewithlove/htaccess.madewithlove.be#59] opened 2018-11-05 22:24 UTC
If the testing .htaccess file is going to be used in production, the file/directory could be scanned for within the actual production site.
So perhaps you could implement a switch for the user to select whether this site can be accessed by anyone on the internet.  If so, the site could be scanned.  Then PHP has a function to test if a file exists.
But mostly people will test with "localhost", or similar...

**Comment by eklingen88** [comment] 2019-01-09 17:42
I would recommend adding a textarea to paste in a directory structure.

Using a basic command like `tree -fFin` on Linux gives a nice output that would be easy to parse for this purpose.  For example (I limited this to a depth of 2 for brevity's sake):

```
.
./wp/
./wp/composer.json
./wp/index.php
./wp/license.txt
./wp/wp-activate.php
./wp/wp-admin/
./wp/wp-blog-header.php
./wp/wp-comments-post.php
./wp/wp-config-sample.php
./wp/wp-content/
./wp/wp-cron.php
./wp/wp-includes/
./wp/wp-links-opml.php
./wp/wp-load.php
./wp/wp-login.php
./wp/wp-mail.php
./wp/wp-settings.php
./wp/wp-signup.php
./wp/wp-trackback.php
./wp/xmlrpc.php
./wp-config.php
./wp-content/
./wp-content/db.php
./wp-content/debug.log
./wp-content/index.php
./wp-content/mu-plugins/
./wp-content/plugins/
./wp-content/themes/
./wp-content/upgrade/
./wp-content/uploads/
./wp-content/wphb-logs/
```

The `tree` command also has the JSON format flag `-J` which would make parsing the structure even easier.

Just some ideas.  I'd be happy to help if that's an option.

**Comment by WouterSioen** [comment] 2019-11-19 10:12
Duplicate of #7

**Closed by WouterSioen** 2019-11-19 10:12 UTC
Labels: enhancement
